apiVersion: apps/v1
kind: Deployment
metadata:
  name: moxy-backend-deployment
  labels:
    app: moxy-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moxy-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: moxy-backend
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: moxy-pool
      containers:
        - name: moxy-backend
          image: gcr.io/moxy-384018/moxy-backend:latest # This will be replaced by the unique tag
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DB_NAME
              value: 'moxy'
            - name: FRONTEND_NEW_PASSWORD_URL
              value: 'http://34.118.78.215/reset-password/new-password'
            - name: MONGODB_CONFIG
              valueFrom:
                secretKeyRef:
                  name: moxy-secrets
                  key: MONGODB_CONFIG
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: moxy-secrets
                  key: PRIVATE_KEY
            - name: GOOGLE_SMTP_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: moxy-secrets
                  key: GOOGLE_SMTP_CLIENT_SECRET
            - name: GOOGLE_SMTP_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: moxy-secrets
                  key: GOOGLE_SMTP_REFRESH_TOKEN
            - name: MAIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: moxy-secrets
                  key: MAIN_EMAIL
            - name: MONOPAY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: moxy-secrets
                  key: MONOPAY_TOKEN
            - name: GOOGLE_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: google-credentials
                  key: google-credentials.json
            - name: FB_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: moxy-secrets
                  key: FB_APP_SECRET
            - name: FB_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: moxy-secrets
                  key: FB_ACCESS_TOKEN
