name: Deploy Backend App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Generate unique tag
        run: echo "UNIQUE_TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Decode and Check Google Credentials
        id: check_credentials
        run: |
          echo $GOOGLE_CREDENTIALS_JSON | base64 -d > google-credentials.json
          cat google-credentials.json
          if ! jq empty google-credentials.json; then
            echo "Google credentials JSON is invalid"
            exit 1
          fi
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

      - name: Build Docker image
        run: |
          echo $GOOGLE_CREDENTIALS_JSON | base64 -d > google-credentials.json
          docker build --build-arg GOOGLE_CREDENTIALS="$(cat google-credentials.json)" -t gcr.io/moxy-384018/moxy-backend:${{ env.UNIQUE_TAG }} -f Dockerfile .
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

      - name: Login to Google Container Registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | base64 -d > decoded_key.json
          cat decoded_key.json | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin https://gcr.io

      - name: Push Docker image to GCR
        run: docker push gcr.io/moxy-384018/moxy-backend:${{ env.UNIQUE_TAG }}

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}

      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v2.0.1

      - name: Install gke-gcloud-auth-plugin
        run: gcloud components install gke-gcloud-auth-plugin

      - name: Create Kubeconfig File
        run: echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - name: Replace image tag in deployment file
        run: |
          sed -i "s|moxy-backend:latest|moxy-backend:${{ env.UNIQUE_TAG }}|g" deployment.yaml

      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment.yaml
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
