name: Deploy Backend App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      unique_tag: ${{ steps.tag.outputs.date }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Generate unique tag
        id: tag
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: Build Docker image
        run: docker build -t gcr.io/moxy-384018/moxy-backend:${{ steps.tag.outputs.date }} -f Dockerfile .

      - name: Login to Google Container Registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | base64 -d > decoded_key.json
          cat decoded_key.json | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin https://gcr.io

      - name: Push Docker image to GCR
        run: docker push gcr.io/moxy-384018/moxy-backend:${{ steps.tag.outputs.date }}

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}

      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v2.0.1

      - name: Install gke-gcloud-auth-plugin
        run: gcloud components install gke-gcloud-auth-plugin

      - name: Create Kubeconfig File
        run: echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - name: Replace image tag in deployment file
        run: |
          sed -i "s|moxy-backend:latest|moxy-backend:${{ steps.tag.outputs.date }}|g" deployment.yaml

      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment.yaml
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
